### ISSUE TITLE
There is not document in this project

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-ansible#1]

**Comment by jiaosir-cn** [comment]
Project: ansible-ansible     -d test
Platform: 阿里云 Ubuntu20.04   AWS Ubuntu20.04
ip: 47.242.221.175  100.25.198.213
Error Installation error
error:
![image](https://user-images.githubusercontent.com/76861519/108475482-b9703c00-72cb-11eb-97b4-28c891f3b62a.png)

**Comment by jiaosir-cn** [comment]
Project: ansible-ansible -d test
Platform:  AWS Linux2
ip: 54.173.174.115
Error Installation error
error:
![image](https://user-images.githubusercontent.com/76861519/108475788-2552a480-72cc-11eb-9be4-bc678db597ea.png)

**Comment by jiaosir-cn** [comment]
Project: ansible-ansible -d test
Platform: 阿里云 CentOS7.9
ip: 47.242.240.178
Smooth installation
Situation：
安装完毕之后 上机测试发现test.yml 项目跑不通
![image](https://user-images.githubusercontent.com/76861519/108477026-abbbb600-72cd-11eb-971b-b24f29c1b20e.png)


加上ansible-playbook -i hosts test.yml -c local 就可以了
 已经通畅。

![image](https://user-images.githubusercontent.com/76861519/108480484-f9d2b880-72d1-11eb-9268-fcda1172f7ff.png)

**Comment by jiaosir-cn** [comment]
Platform: 阿里云 CentOS7.9
ip: 47.242.240.178
加上ansible-playbook -i hosts test.yml -c local  就可以了
阿里云 CentOS7.9  已经通畅。

**Comment by morning-tan** [comment]
Document (EN) 请优先补充。特别是安装部署章节。以便商品在AWS上架审核。

**Comment by chendelin1982** [comment]
solution-cli 未翻译
