### ISSUE TITLE
简介内容有误

### ISSUE THREAD

**Issue by morning-tan** [Websoft9/ansible-ansible#6]
## Language

- [ ] Chinese
- [x] English

## Content error

Provide us with documentation errors, e.g spelling mistake, wrong screenshot, code syntax error.

* URL: http://support.websoft9.com/docs/ansible/
* Description: 关于产品的概述错误
* Screenshot
* 
![image](https://user-images.githubusercontent.com/54173243/126771326-abfaadd6-1e4b-4fc2-8e56-017c3001ac12.png)

## Content optimization

Provide us with content optimization, e.g easy to read, simplify the steps, step by step, precise expression.

* URL: 
* Description: 

## New content

Describe important content what do you think is important in this documentation.

**What content do you want to add?**  

(describe here) 

**Steps for the content**  

4. Modify file '....'

**Comment by chendelin1982** [comment]
Done
